name: union_example
description: Example usages of the union_utils library.

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  union_annotation: ^2.5.0

dev_dependencies:
  build_runner: ^2.3.3
  union_generator: ^2.5.0
