name: union_example
description: Example usages of the union_utils package.

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  union_annotation:
    git:
      url: https://github.com/tomwyr/union_utils.git
      path: union_annotation
      ref: v2.4.0

dev_dependencies:
  build_runner: ^2.3.3
  union_generator:
    git:
      url: https://github.com/tomwyr/union_utils.git
      path: union_generator
      ref: v2.4.0
