name: union_example
description: Example usages of the union_utils package.

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  union:
    path: ../union

dev_dependencies:
  build_runner: ^2.3.3
  union_generator:
    path: ../union_generator
