name: union_annotation
description: Annotations and public types for union_utils, a library allowing to generate utilities for union types.
repository: https://github.com/tomwyr/union_utils
version: 2.5.3

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  meta: ^1.9.1
