builders:
  union_generator:
    import: "package:union_generator/src/builder.dart"
    builder_factories: ["unionGenerator"]
    build_extensions: {".dart": ["union_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
