name: union_generator
description: Code generator for the union_utils, a library allowing to generate utilities for union types.
repository: https://github.com/tomwyr/union_utils
version: 2.5.2

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  analyzer: ^5.10.0
  build: ^2.3.1
  collection: ^1.17.1
  source_gen: ^1.2.7
  union_annotation: ^2.5.2
