name: union_generator
description: Code generator for the Union package.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  analyzer: ^5.6.0
  build: ^2.3.1
  collection: ^1.17.0
  source_gen: ^1.2.7
  union:
    git:
      url: https://github.com/tomwyr/union.git
      path: union
      ref: v1.0.1
