name: example
description: Example usages of the Union package.

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  union:
    git:
      url: https://github.com/tomwyr/union.git
      path: union
      ref: v1.0.1

dev_dependencies:
  build_runner: ^2.3.3
  union_generator:
    git:
      url: https://github.com/tomwyr/union.git
      path: union_generator
      ref: v1.0.1
